### ISSUE TITLE
Comma is not escaped properly

### ISSUE THREAD

**Issue by ghost** [nityanarayan44/Extension#1]
Steps to reproduce:
1/ Install extension on Chrome Version 62.0.3202.89 (Official Build) (64-bit)
2/ Open any website, say http://nityanarayan44.blogspot.in/2017/11/how-to-add-unpacked-chrome-extension.html
3/ Click on extension to find XPath.
4/ Now click on title of web page containing text "Hello World,"
5/ Comma "," is missed by suggested xpath
Suggested XPath:
//*[text()='Hello World'] 
Expected XPath:
//*[text()='Hello World,']

**Comment by nityanarayan44** [comment]
This is a clone of issue #2. 
It will be considered in the future release.
