### ISSUE TITLE
Double quotes and single quotes are not escaped properly

### ISSUE THREAD

**Issue by ghost** [nityanarayan44/Extension#2]
Steps to reproduce:
1/ Install extension on Chrome Version 62.0.3202.89 (Official Build) (64-bit)
2/ Open any website, say http://nityanarayan44.blogspot.in/2017/11/how-to-add-unpacked-chrome-extension.html
3/ Click on extension to find XPath.
4/ Now click on any line of of text which contains double quotes, say "So let's know first, what is "Unpacked Chrome Extension" and "Packed Chrome Extension"?" one.
5/ Observe the suggested XPath is missing double quotes and single quote in suggested xpath.
Suggested XPATH:
  //*[text()='So lets know first what is Unpacked Chrome Extension and Packed Chrome Extension']

**Comment by nityanarayan44** [comment]
Currently, It is excluded by me[to avoid the special chars processing].
I will include this in the later release.

thanks for bringing this issue to my attention @devajitsingh .
